#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="qds0270282_db")]
	public partial class PianoDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdornment(Adornment instance);
    partial void UpdateAdornment(Adornment instance);
    partial void DeleteAdornment(Adornment instance);
    partial void InsertOpus(Opus instance);
    partial void UpdateOpus(Opus instance);
    partial void DeleteOpus(Opus instance);
    partial void InsertOpusComment(OpusComment instance);
    partial void UpdateOpusComment(OpusComment instance);
    partial void DeleteOpusComment(OpusComment instance);
    partial void InsertUsersAdornment(UsersAdornment instance);
    partial void UpdateUsersAdornment(UsersAdornment instance);
    partial void DeleteUsersAdornment(UsersAdornment instance);
    partial void InsertHouse(House instance);
    partial void UpdateHouse(House instance);
    partial void DeleteHouse(House instance);
    partial void InsertAttention(Attention instance);
    partial void UpdateAttention(Attention instance);
    partial void DeleteAttention(Attention instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public PianoDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pianoWebConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adornment> Adornment
		{
			get
			{
				return this.GetTable<Adornment>();
			}
		}
		
		public System.Data.Linq.Table<AlbumUpdate> AlbumUpdate
		{
			get
			{
				return this.GetTable<AlbumUpdate>();
			}
		}
		
		public System.Data.Linq.Table<Config> Config
		{
			get
			{
				return this.GetTable<Config>();
			}
		}
		
		public System.Data.Linq.Table<Opus> Opus
		{
			get
			{
				return this.GetTable<Opus>();
			}
		}
		
		public System.Data.Linq.Table<OpusComment> OpusComment
		{
			get
			{
				return this.GetTable<OpusComment>();
			}
		}
		
		public System.Data.Linq.Table<UsersAdornment> UsersAdornment
		{
			get
			{
				return this.GetTable<UsersAdornment>();
			}
		}
		
		public System.Data.Linq.Table<House> House
		{
			get
			{
				return this.GetTable<House>();
			}
		}
		
		public System.Data.Linq.Table<Attention> Attention
		{
			get
			{
				return this.GetTable<Attention>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[Table(Name="dbo.Adornment")]
	public partial class Adornment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<short> _type;
		
		private string _name;
		
		private string _imagePath;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntitySet<UsersAdornment> _UsersAdornment;
		
		private EntitySet<House> _House;
		
		private EntitySet<House> _House1;
		
		private EntitySet<House> _House2;
		
		private EntitySet<House> _House3;
		
		private EntitySet<House> _House4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OntypeChanging(System.Nullable<short> value);
    partial void OntypeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnimagePathChanging(string value);
    partial void OnimagePathChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Adornment()
		{
			this._UsersAdornment = new EntitySet<UsersAdornment>(new Action<UsersAdornment>(this.attach_UsersAdornment), new Action<UsersAdornment>(this.detach_UsersAdornment));
			this._House = new EntitySet<House>(new Action<House>(this.attach_House), new Action<House>(this.detach_House));
			this._House1 = new EntitySet<House>(new Action<House>(this.attach_House1), new Action<House>(this.detach_House1));
			this._House2 = new EntitySet<House>(new Action<House>(this.attach_House2), new Action<House>(this.detach_House2));
			this._House3 = new EntitySet<House>(new Action<House>(this.attach_House3), new Action<House>(this.detach_House3));
			this._House4 = new EntitySet<House>(new Action<House>(this.attach_House4), new Action<House>(this.detach_House4));
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_type", DbType="SmallInt")]
		public System.Nullable<short> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_imagePath", DbType="VarChar(500)")]
		public string imagePath
		{
			get
			{
				return this._imagePath;
			}
			set
			{
				if ((this._imagePath != value))
				{
					this.OnimagePathChanging(value);
					this.SendPropertyChanging();
					this._imagePath = value;
					this.SendPropertyChanged("imagePath");
					this.OnimagePathChanged();
				}
			}
		}
		
		[Column(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Adornment_UsersAdornment", Storage="_UsersAdornment", ThisKey="ID", OtherKey="adornmentID")]
		public EntitySet<UsersAdornment> UsersAdornment
		{
			get
			{
				return this._UsersAdornment;
			}
			set
			{
				this._UsersAdornment.Assign(value);
			}
		}
		
		[Association(Name="Adornment_House", Storage="_House", ThisKey="ID", OtherKey="floorID")]
		public EntitySet<House> House
		{
			get
			{
				return this._House;
			}
			set
			{
				this._House.Assign(value);
			}
		}
		
		[Association(Name="Adornment_House1", Storage="_House1", ThisKey="ID", OtherKey="frescoID")]
		public EntitySet<House> House1
		{
			get
			{
				return this._House1;
			}
			set
			{
				this._House1.Assign(value);
			}
		}
		
		[Association(Name="Adornment_House2", Storage="_House2", ThisKey="ID", OtherKey="pendantLampID")]
		public EntitySet<House> House2
		{
			get
			{
				return this._House2;
			}
			set
			{
				this._House2.Assign(value);
			}
		}
		
		[Association(Name="Adornment_House3", Storage="_House3", ThisKey="ID", OtherKey="pianoID")]
		public EntitySet<House> House3
		{
			get
			{
				return this._House3;
			}
			set
			{
				this._House3.Assign(value);
			}
		}
		
		[Association(Name="Adornment_House4", Storage="_House4", ThisKey="ID", OtherKey="sofaID")]
		public EntitySet<House> House4
		{
			get
			{
				return this._House4;
			}
			set
			{
				this._House4.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UsersAdornment(UsersAdornment entity)
		{
			this.SendPropertyChanging();
			entity.Adornment = this;
		}
		
		private void detach_UsersAdornment(UsersAdornment entity)
		{
			this.SendPropertyChanging();
			entity.Adornment = null;
		}
		
		private void attach_House(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment = this;
		}
		
		private void detach_House(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment = null;
		}
		
		private void attach_House1(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment1 = this;
		}
		
		private void detach_House1(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment1 = null;
		}
		
		private void attach_House2(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment2 = this;
		}
		
		private void detach_House2(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment2 = null;
		}
		
		private void attach_House3(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment3 = this;
		}
		
		private void detach_House3(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment3 = null;
		}
		
		private void attach_House4(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment4 = this;
		}
		
		private void detach_House4(House entity)
		{
			this.SendPropertyChanging();
			entity.Adornment4 = null;
		}
	}
	
	[Table(Name="dbo.AlbumUpdate")]
	public partial class AlbumUpdate
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private string _name;
		
		private string _zipPath;
		
		private System.Nullable<System.Guid> _serialNo;
		
		private string _userName;
		
		private System.Nullable<System.DateTime> _downloadDate;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public AlbumUpdate()
		{
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier", IsDbGenerated=true)]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_zipPath", DbType="VarChar(500)")]
		public string zipPath
		{
			get
			{
				return this._zipPath;
			}
			set
			{
				if ((this._zipPath != value))
				{
					this._zipPath = value;
				}
			}
		}
		
		[Column(Storage="_serialNo", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> serialNo
		{
			get
			{
				return this._serialNo;
			}
			set
			{
				if ((this._serialNo != value))
				{
					this._serialNo = value;
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_downloadDate", DbType="Date")]
		public System.Nullable<System.DateTime> downloadDate
		{
			get
			{
				return this._downloadDate;
			}
			set
			{
				if ((this._downloadDate != value))
				{
					this._downloadDate = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Config")]
	public partial class Config
	{
		
		private string _name;
		
		private string _memo;
		
		private System.Nullable<bool> _turnOn;
		
		public Config()
		{
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_memo", DbType="VarChar(500)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this._memo = value;
				}
			}
		}
		
		[Column(Storage="_turnOn", DbType="Bit")]
		public System.Nullable<bool> turnOn
		{
			get
			{
				return this._turnOn;
			}
			set
			{
				if ((this._turnOn != value))
				{
					this._turnOn = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Opus")]
	public partial class Opus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _name;
		
		private string _userName;
		
		private string _mp3Path;
		
		private System.Nullable<int> _clickCount;
		
		private System.Nullable<int> _likeCount;
		
		private System.Nullable<int> _score;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntitySet<OpusComment> _OpusComment;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void Onmp3PathChanging(string value);
    partial void Onmp3PathChanged();
    partial void OnclickCountChanging(System.Nullable<int> value);
    partial void OnclickCountChanged();
    partial void OnlikeCountChanging(System.Nullable<int> value);
    partial void OnlikeCountChanged();
    partial void OnscoreChanging(System.Nullable<int> value);
    partial void OnscoreChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Opus()
		{
			this._OpusComment = new EntitySet<OpusComment>(new Action<OpusComment>(this.attach_OpusComment), new Action<OpusComment>(this.detach_OpusComment));
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_mp3Path", DbType="VarChar(500)")]
		public string mp3Path
		{
			get
			{
				return this._mp3Path;
			}
			set
			{
				if ((this._mp3Path != value))
				{
					this.Onmp3PathChanging(value);
					this.SendPropertyChanging();
					this._mp3Path = value;
					this.SendPropertyChanged("mp3Path");
					this.Onmp3PathChanged();
				}
			}
		}
		
		[Column(Storage="_clickCount", DbType="Int")]
		public System.Nullable<int> clickCount
		{
			get
			{
				return this._clickCount;
			}
			set
			{
				if ((this._clickCount != value))
				{
					this.OnclickCountChanging(value);
					this.SendPropertyChanging();
					this._clickCount = value;
					this.SendPropertyChanged("clickCount");
					this.OnclickCountChanged();
				}
			}
		}
		
		[Column(Storage="_likeCount", DbType="Int")]
		public System.Nullable<int> likeCount
		{
			get
			{
				return this._likeCount;
			}
			set
			{
				if ((this._likeCount != value))
				{
					this.OnlikeCountChanging(value);
					this.SendPropertyChanging();
					this._likeCount = value;
					this.SendPropertyChanged("likeCount");
					this.OnlikeCountChanged();
				}
			}
		}
		
		[Column(Storage="_score", DbType="Int")]
		public System.Nullable<int> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Opus_OpusComment", Storage="_OpusComment", ThisKey="ID", OtherKey="opusID")]
		public EntitySet<OpusComment> OpusComment
		{
			get
			{
				return this._OpusComment;
			}
			set
			{
				this._OpusComment.Assign(value);
			}
		}
		
		[Association(Name="Users_Opus", Storage="_Users", ThisKey="userName", OtherKey="userName", IsForeignKey=true, DeleteRule="CASCADE")]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.Opus.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.Opus.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OpusComment(OpusComment entity)
		{
			this.SendPropertyChanging();
			entity.Opus = this;
		}
		
		private void detach_OpusComment(OpusComment entity)
		{
			this.SendPropertyChanging();
			entity.Opus = null;
		}
	}
	
	[Table(Name="dbo.OpusComment")]
	public partial class OpusComment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _commentID;
		
		private string _userName;
		
		private System.Nullable<System.Guid> _opusID;
		
		private string _comment;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntityRef<Opus> _Opus;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncommentIDChanging(System.Guid value);
    partial void OncommentIDChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnopusIDChanging(System.Nullable<System.Guid> value);
    partial void OnopusIDChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public OpusComment()
		{
			this._Opus = default(EntityRef<Opus>);
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_commentID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid commentID
		{
			get
			{
				return this._commentID;
			}
			set
			{
				if ((this._commentID != value))
				{
					this.OncommentIDChanging(value);
					this.SendPropertyChanging();
					this._commentID = value;
					this.SendPropertyChanged("commentID");
					this.OncommentIDChanged();
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_opusID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> opusID
		{
			get
			{
				return this._opusID;
			}
			set
			{
				if ((this._opusID != value))
				{
					if (this._Opus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnopusIDChanging(value);
					this.SendPropertyChanging();
					this._opusID = value;
					this.SendPropertyChanged("opusID");
					this.OnopusIDChanged();
				}
			}
		}
		
		[Column(Storage="_comment", DbType="VarChar(500)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date")]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Opus_OpusComment", Storage="_Opus", ThisKey="opusID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Opus Opus
		{
			get
			{
				return this._Opus.Entity;
			}
			set
			{
				Opus previousValue = this._Opus.Entity;
				if (((previousValue != value) 
							|| (this._Opus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Opus.Entity = null;
						previousValue.OpusComment.Remove(this);
					}
					this._Opus.Entity = value;
					if ((value != null))
					{
						value.OpusComment.Add(this);
						this._opusID = value.ID;
					}
					else
					{
						this._opusID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Opus");
				}
			}
		}
		
		[Association(Name="Users_OpusComment", Storage="_Users", ThisKey="userName", OtherKey="userName", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.OpusComment.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.OpusComment.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.UsersAdornment")]
	public partial class UsersAdornment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private System.Guid _adornmentID;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntityRef<Adornment> _Adornment;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnadornmentIDChanging(System.Guid value);
    partial void OnadornmentIDChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public UsersAdornment()
		{
			this._Adornment = default(EntityRef<Adornment>);
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_adornmentID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid adornmentID
		{
			get
			{
				return this._adornmentID;
			}
			set
			{
				if ((this._adornmentID != value))
				{
					if (this._Adornment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnadornmentIDChanging(value);
					this.SendPropertyChanging();
					this._adornmentID = value;
					this.SendPropertyChanged("adornmentID");
					this.OnadornmentIDChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Adornment_UsersAdornment", Storage="_Adornment", ThisKey="adornmentID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment
		{
			get
			{
				return this._Adornment.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment.Entity;
				if (((previousValue != value) 
							|| (this._Adornment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment.Entity = null;
						previousValue.UsersAdornment.Remove(this);
					}
					this._Adornment.Entity = value;
					if ((value != null))
					{
						value.UsersAdornment.Add(this);
						this._adornmentID = value.ID;
					}
					else
					{
						this._adornmentID = default(System.Guid);
					}
					this.SendPropertyChanged("Adornment");
				}
			}
		}
		
		[Association(Name="Users_UsersAdornment", Storage="_Users", ThisKey="userName", OtherKey="userName", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.UsersAdornment.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.UsersAdornment.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.House")]
	public partial class House : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _house_id;
		
		private string _userName;
		
		private System.Nullable<System.Guid> _pianoID;
		
		private System.Nullable<System.Guid> _sofaID;
		
		private System.Nullable<System.Guid> _frescoID;
		
		private System.Nullable<System.Guid> _floorID;
		
		private System.Nullable<System.Guid> _pendantLampID;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntityRef<Adornment> _Adornment;
		
		private EntityRef<Adornment> _Adornment1;
		
		private EntityRef<Adornment> _Adornment2;
		
		private EntityRef<Adornment> _Adornment3;
		
		private EntityRef<Adornment> _Adornment4;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhouse_idChanging(int value);
    partial void Onhouse_idChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpianoIDChanging(System.Nullable<System.Guid> value);
    partial void OnpianoIDChanged();
    partial void OnsofaIDChanging(System.Nullable<System.Guid> value);
    partial void OnsofaIDChanged();
    partial void OnfrescoIDChanging(System.Nullable<System.Guid> value);
    partial void OnfrescoIDChanged();
    partial void OnfloorIDChanging(System.Nullable<System.Guid> value);
    partial void OnfloorIDChanged();
    partial void OnpendantLampIDChanging(System.Nullable<System.Guid> value);
    partial void OnpendantLampIDChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public House()
		{
			this._Adornment = default(EntityRef<Adornment>);
			this._Adornment1 = default(EntityRef<Adornment>);
			this._Adornment2 = default(EntityRef<Adornment>);
			this._Adornment3 = default(EntityRef<Adornment>);
			this._Adornment4 = default(EntityRef<Adornment>);
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_house_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int house_id
		{
			get
			{
				return this._house_id;
			}
			set
			{
				if ((this._house_id != value))
				{
					this.Onhouse_idChanging(value);
					this.SendPropertyChanging();
					this._house_id = value;
					this.SendPropertyChanged("house_id");
					this.Onhouse_idChanged();
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_pianoID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pianoID
		{
			get
			{
				return this._pianoID;
			}
			set
			{
				if ((this._pianoID != value))
				{
					if (this._Adornment3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpianoIDChanging(value);
					this.SendPropertyChanging();
					this._pianoID = value;
					this.SendPropertyChanged("pianoID");
					this.OnpianoIDChanged();
				}
			}
		}
		
		[Column(Storage="_sofaID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> sofaID
		{
			get
			{
				return this._sofaID;
			}
			set
			{
				if ((this._sofaID != value))
				{
					if (this._Adornment4.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsofaIDChanging(value);
					this.SendPropertyChanging();
					this._sofaID = value;
					this.SendPropertyChanged("sofaID");
					this.OnsofaIDChanged();
				}
			}
		}
		
		[Column(Storage="_frescoID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> frescoID
		{
			get
			{
				return this._frescoID;
			}
			set
			{
				if ((this._frescoID != value))
				{
					if (this._Adornment1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfrescoIDChanging(value);
					this.SendPropertyChanging();
					this._frescoID = value;
					this.SendPropertyChanged("frescoID");
					this.OnfrescoIDChanged();
				}
			}
		}
		
		[Column(Storage="_floorID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> floorID
		{
			get
			{
				return this._floorID;
			}
			set
			{
				if ((this._floorID != value))
				{
					if (this._Adornment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfloorIDChanging(value);
					this.SendPropertyChanging();
					this._floorID = value;
					this.SendPropertyChanged("floorID");
					this.OnfloorIDChanged();
				}
			}
		}
		
		[Column(Storage="_pendantLampID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pendantLampID
		{
			get
			{
				return this._pendantLampID;
			}
			set
			{
				if ((this._pendantLampID != value))
				{
					if (this._Adornment2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpendantLampIDChanging(value);
					this.SendPropertyChanging();
					this._pendantLampID = value;
					this.SendPropertyChanged("pendantLampID");
					this.OnpendantLampIDChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Adornment_House", Storage="_Adornment", ThisKey="floorID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment
		{
			get
			{
				return this._Adornment.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment.Entity;
				if (((previousValue != value) 
							|| (this._Adornment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment.Entity = null;
						previousValue.House.Remove(this);
					}
					this._Adornment.Entity = value;
					if ((value != null))
					{
						value.House.Add(this);
						this._floorID = value.ID;
					}
					else
					{
						this._floorID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Adornment");
				}
			}
		}
		
		[Association(Name="Adornment_House1", Storage="_Adornment1", ThisKey="frescoID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment1
		{
			get
			{
				return this._Adornment1.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment1.Entity;
				if (((previousValue != value) 
							|| (this._Adornment1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment1.Entity = null;
						previousValue.House1.Remove(this);
					}
					this._Adornment1.Entity = value;
					if ((value != null))
					{
						value.House1.Add(this);
						this._frescoID = value.ID;
					}
					else
					{
						this._frescoID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Adornment1");
				}
			}
		}
		
		[Association(Name="Adornment_House2", Storage="_Adornment2", ThisKey="pendantLampID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment2
		{
			get
			{
				return this._Adornment2.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment2.Entity;
				if (((previousValue != value) 
							|| (this._Adornment2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment2.Entity = null;
						previousValue.House2.Remove(this);
					}
					this._Adornment2.Entity = value;
					if ((value != null))
					{
						value.House2.Add(this);
						this._pendantLampID = value.ID;
					}
					else
					{
						this._pendantLampID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Adornment2");
				}
			}
		}
		
		[Association(Name="Adornment_House3", Storage="_Adornment3", ThisKey="pianoID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment3
		{
			get
			{
				return this._Adornment3.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment3.Entity;
				if (((previousValue != value) 
							|| (this._Adornment3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment3.Entity = null;
						previousValue.House3.Remove(this);
					}
					this._Adornment3.Entity = value;
					if ((value != null))
					{
						value.House3.Add(this);
						this._pianoID = value.ID;
					}
					else
					{
						this._pianoID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Adornment3");
				}
			}
		}
		
		[Association(Name="Adornment_House4", Storage="_Adornment4", ThisKey="sofaID", OtherKey="ID", IsForeignKey=true)]
		public Adornment Adornment4
		{
			get
			{
				return this._Adornment4.Entity;
			}
			set
			{
				Adornment previousValue = this._Adornment4.Entity;
				if (((previousValue != value) 
							|| (this._Adornment4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adornment4.Entity = null;
						previousValue.House4.Remove(this);
					}
					this._Adornment4.Entity = value;
					if ((value != null))
					{
						value.House4.Add(this);
						this._sofaID = value.ID;
					}
					else
					{
						this._sofaID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Adornment4");
				}
			}
		}
		
		[Association(Name="Users_House", Storage="_Users", ThisKey="userName", OtherKey="userName", IsForeignKey=true, DeleteRule="CASCADE")]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.House.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.House.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Attention")]
	public partial class Attention : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _attentionUser;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntityRef<Users> _Users;
		
		private EntityRef<Users> _Users1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnattentionUserChanging(string value);
    partial void OnattentionUserChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Attention()
		{
			this._Users = default(EntityRef<Users>);
			this._Users1 = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_attentionUser", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string attentionUser
		{
			get
			{
				return this._attentionUser;
			}
			set
			{
				if ((this._attentionUser != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnattentionUserChanging(value);
					this.SendPropertyChanging();
					this._attentionUser = value;
					this.SendPropertyChanged("attentionUser");
					this.OnattentionUserChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date")]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Users_Attention", Storage="_Users", ThisKey="attentionUser", OtherKey="userName", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.Attention.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.Attention.Add(this);
						this._attentionUser = value.userName;
					}
					else
					{
						this._attentionUser = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		[Association(Name="Users_Attention1", Storage="_Users1", ThisKey="userName", OtherKey="userName", IsForeignKey=true)]
		public Users Users1
		{
			get
			{
				return this._Users1.Entity;
			}
			set
			{
				Users previousValue = this._Users1.Entity;
				if (((previousValue != value) 
							|| (this._Users1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users1.Entity = null;
						previousValue.Attention1.Remove(this);
					}
					this._Users1.Entity = value;
					if ((value != null))
					{
						value.Attention1.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _password;
		
		private System.Nullable<byte> _gender;
		
		private string _email;
		
		private string _address;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _constellation;
		
		private System.Nullable<int> _scroe;
		
		private System.Nullable<short> _pianoLevel;
		
		private string _memo;
		
		private string _sinaWeiBo;
		
		private string _qq;
		
		private string _tencentWeiBo;
		
		private System.Nullable<System.DateTime> _dModified;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private long _landingDays;
		
		private EntitySet<Opus> _Opus;
		
		private EntitySet<OpusComment> _OpusComment;
		
		private EntitySet<UsersAdornment> _UsersAdornment;
		
		private EntitySet<House> _House;
		
		private EntitySet<Attention> _Attention;
		
		private EntitySet<Attention> _Attention1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngenderChanging(System.Nullable<byte> value);
    partial void OngenderChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnconstellationChanging(string value);
    partial void OnconstellationChanged();
    partial void OnscroeChanging(System.Nullable<int> value);
    partial void OnscroeChanged();
    partial void OnpianoLevelChanging(System.Nullable<short> value);
    partial void OnpianoLevelChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    partial void OnsinaWeiBoChanging(string value);
    partial void OnsinaWeiBoChanged();
    partial void OnqqChanging(string value);
    partial void OnqqChanged();
    partial void OntencentWeiBoChanging(string value);
    partial void OntencentWeiBoChanged();
    partial void OndModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OndModifiedChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    partial void OnlandingDaysChanging(long value);
    partial void OnlandingDaysChanged();
    #endregion
		
		public Users()
		{
			this._Opus = new EntitySet<Opus>(new Action<Opus>(this.attach_Opus), new Action<Opus>(this.detach_Opus));
			this._OpusComment = new EntitySet<OpusComment>(new Action<OpusComment>(this.attach_OpusComment), new Action<OpusComment>(this.detach_OpusComment));
			this._UsersAdornment = new EntitySet<UsersAdornment>(new Action<UsersAdornment>(this.attach_UsersAdornment), new Action<UsersAdornment>(this.detach_UsersAdornment));
			this._House = new EntitySet<House>(new Action<House>(this.attach_House), new Action<House>(this.detach_House));
			this._Attention = new EntitySet<Attention>(new Action<Attention>(this.attach_Attention), new Action<Attention>(this.detach_Attention));
			this._Attention1 = new EntitySet<Attention>(new Action<Attention>(this.attach_Attention1), new Action<Attention>(this.detach_Attention1));
			OnCreated();
		}
		
		[Column(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_gender", DbType="TinyInt")]
		public System.Nullable<byte> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[Column(Storage="_constellation", DbType="Char(10)")]
		public string constellation
		{
			get
			{
				return this._constellation;
			}
			set
			{
				if ((this._constellation != value))
				{
					this.OnconstellationChanging(value);
					this.SendPropertyChanging();
					this._constellation = value;
					this.SendPropertyChanged("constellation");
					this.OnconstellationChanged();
				}
			}
		}
		
		[Column(Storage="_scroe", DbType="Int")]
		public System.Nullable<int> scroe
		{
			get
			{
				return this._scroe;
			}
			set
			{
				if ((this._scroe != value))
				{
					this.OnscroeChanging(value);
					this.SendPropertyChanging();
					this._scroe = value;
					this.SendPropertyChanged("scroe");
					this.OnscroeChanged();
				}
			}
		}
		
		[Column(Storage="_pianoLevel", DbType="SmallInt")]
		public System.Nullable<short> pianoLevel
		{
			get
			{
				return this._pianoLevel;
			}
			set
			{
				if ((this._pianoLevel != value))
				{
					this.OnpianoLevelChanging(value);
					this.SendPropertyChanging();
					this._pianoLevel = value;
					this.SendPropertyChanged("pianoLevel");
					this.OnpianoLevelChanged();
				}
			}
		}
		
		[Column(Storage="_memo", DbType="VarChar(500)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		[Column(Storage="_sinaWeiBo", DbType="VarChar(100)")]
		public string sinaWeiBo
		{
			get
			{
				return this._sinaWeiBo;
			}
			set
			{
				if ((this._sinaWeiBo != value))
				{
					this.OnsinaWeiBoChanging(value);
					this.SendPropertyChanging();
					this._sinaWeiBo = value;
					this.SendPropertyChanged("sinaWeiBo");
					this.OnsinaWeiBoChanged();
				}
			}
		}
		
		[Column(Storage="_qq", DbType="Char(20)")]
		public string qq
		{
			get
			{
				return this._qq;
			}
			set
			{
				if ((this._qq != value))
				{
					this.OnqqChanging(value);
					this.SendPropertyChanging();
					this._qq = value;
					this.SendPropertyChanged("qq");
					this.OnqqChanged();
				}
			}
		}
		
		[Column(Storage="_tencentWeiBo", DbType="VarChar(100)")]
		public string tencentWeiBo
		{
			get
			{
				return this._tencentWeiBo;
			}
			set
			{
				if ((this._tencentWeiBo != value))
				{
					this.OntencentWeiBoChanging(value);
					this.SendPropertyChanging();
					this._tencentWeiBo = value;
					this.SendPropertyChanged("tencentWeiBo");
					this.OntencentWeiBoChanged();
				}
			}
		}
		
		[Column(Storage="_dModified", DbType="Date")]
		public System.Nullable<System.DateTime> dModified
		{
			get
			{
				return this._dModified;
			}
			set
			{
				if ((this._dModified != value))
				{
					this.OndModifiedChanging(value);
					this.SendPropertyChanging();
					this._dModified = value;
					this.SendPropertyChanged("dModified");
					this.OndModifiedChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Column(Storage="_landingDays", DbType="BigInt")]
		public long landingDays
		{
			get
			{
				return this._landingDays;
			}
			set
			{
				if ((this._landingDays != value))
				{
					this.OnlandingDaysChanging(value);
					this.SendPropertyChanging();
					this._landingDays = value;
					this.SendPropertyChanged("landingDays");
					this.OnlandingDaysChanged();
				}
			}
		}
		
		[Association(Name="Users_Opus", Storage="_Opus", ThisKey="userName", OtherKey="userName")]
		public EntitySet<Opus> Opus
		{
			get
			{
				return this._Opus;
			}
			set
			{
				this._Opus.Assign(value);
			}
		}
		
		[Association(Name="Users_OpusComment", Storage="_OpusComment", ThisKey="userName", OtherKey="userName")]
		public EntitySet<OpusComment> OpusComment
		{
			get
			{
				return this._OpusComment;
			}
			set
			{
				this._OpusComment.Assign(value);
			}
		}
		
		[Association(Name="Users_UsersAdornment", Storage="_UsersAdornment", ThisKey="userName", OtherKey="userName")]
		public EntitySet<UsersAdornment> UsersAdornment
		{
			get
			{
				return this._UsersAdornment;
			}
			set
			{
				this._UsersAdornment.Assign(value);
			}
		}
		
		[Association(Name="Users_House", Storage="_House", ThisKey="userName", OtherKey="userName")]
		public EntitySet<House> House
		{
			get
			{
				return this._House;
			}
			set
			{
				this._House.Assign(value);
			}
		}
		
		[Association(Name="Users_Attention", Storage="_Attention", ThisKey="userName", OtherKey="attentionUser")]
		public EntitySet<Attention> Attention
		{
			get
			{
				return this._Attention;
			}
			set
			{
				this._Attention.Assign(value);
			}
		}
		
		[Association(Name="Users_Attention1", Storage="_Attention1", ThisKey="userName", OtherKey="userName")]
		public EntitySet<Attention> Attention1
		{
			get
			{
				return this._Attention1;
			}
			set
			{
				this._Attention1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opus(Opus entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_Opus(Opus entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_OpusComment(OpusComment entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_OpusComment(OpusComment entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_UsersAdornment(UsersAdornment entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_UsersAdornment(UsersAdornment entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_House(House entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_House(House entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_Attention(Attention entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_Attention(Attention entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_Attention1(Attention entity)
		{
			this.SendPropertyChanging();
			entity.Users1 = this;
		}
		
		private void detach_Attention1(Attention entity)
		{
			this.SendPropertyChanging();
			entity.Users1 = null;
		}
	}
}
#pragma warning restore 1591
