#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="pianoWeb")]
	public partial class PianoDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdornment(Adornment instance);
    partial void UpdateAdornment(Adornment instance);
    partial void DeleteAdornment(Adornment instance);
    partial void InsertOpus(Opus instance);
    partial void UpdateOpus(Opus instance);
    partial void DeleteOpus(Opus instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public PianoDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["pianoWebConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PianoDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adornment> Adornment
		{
			get
			{
				return this.GetTable<Adornment>();
			}
		}
		
		public System.Data.Linq.Table<UsersAdornment> UsersAdornment
		{
			get
			{
				return this.GetTable<UsersAdornment>();
			}
		}
		
		public System.Data.Linq.Table<AlbumUpdate> AlbumUpdate
		{
			get
			{
				return this.GetTable<AlbumUpdate>();
			}
		}
		
		public System.Data.Linq.Table<Attention> Attention
		{
			get
			{
				return this.GetTable<Attention>();
			}
		}
		
		public System.Data.Linq.Table<Config> Config
		{
			get
			{
				return this.GetTable<Config>();
			}
		}
		
		public System.Data.Linq.Table<House> House
		{
			get
			{
				return this.GetTable<House>();
			}
		}
		
		public System.Data.Linq.Table<Opus> Opus
		{
			get
			{
				return this.GetTable<Opus>();
			}
		}
		
		public System.Data.Linq.Table<OpusComment> OpusComment
		{
			get
			{
				return this.GetTable<OpusComment>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[Table(Name="dbo.Adornment")]
	public partial class Adornment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<short> _type;
		
		private string _name;
		
		private string _imagePath;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<System.DateTime> _dCreate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OntypeChanging(System.Nullable<short> value);
    partial void OntypeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnimagePathChanging(string value);
    partial void OnimagePathChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Adornment()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_type", DbType="SmallInt")]
		public System.Nullable<short> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_imagePath", DbType="VarChar(500)")]
		public string imagePath
		{
			get
			{
				return this._imagePath;
			}
			set
			{
				if ((this._imagePath != value))
				{
					this.OnimagePathChanging(value);
					this.SendPropertyChanging();
					this._imagePath = value;
					this.SendPropertyChanged("imagePath");
					this.OnimagePathChanged();
				}
			}
		}
		
		[Column(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.UsersAdornment")]
	public partial class UsersAdornment
	{
		
		private string _userName;
		
		private System.Nullable<System.Guid> _adornmentID;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public UsersAdornment()
		{
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_adornmentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> adornmentID
		{
			get
			{
				return this._adornmentID;
			}
			set
			{
				if ((this._adornmentID != value))
				{
					this._adornmentID = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.AlbumUpdate")]
	public partial class AlbumUpdate
	{
		
		private System.Nullable<System.Guid> _ID;
		
		private string _name;
		
		private string _zipPath;
		
		private System.Nullable<System.Guid> _serialNo;
		
		private string _userName;
		
		private System.Nullable<System.DateTime> _downloadDate;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public AlbumUpdate()
		{
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier", IsDbGenerated=true)]
		public System.Nullable<System.Guid> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_zipPath", DbType="VarChar(500)")]
		public string zipPath
		{
			get
			{
				return this._zipPath;
			}
			set
			{
				if ((this._zipPath != value))
				{
					this._zipPath = value;
				}
			}
		}
		
		[Column(Storage="_serialNo", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> serialNo
		{
			get
			{
				return this._serialNo;
			}
			set
			{
				if ((this._serialNo != value))
				{
					this._serialNo = value;
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_downloadDate", DbType="Date")]
		public System.Nullable<System.DateTime> downloadDate
		{
			get
			{
				return this._downloadDate;
			}
			set
			{
				if ((this._downloadDate != value))
				{
					this._downloadDate = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Attention")]
	public partial class Attention
	{
		
		private string _userName;
		
		private string _attentionUser;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public Attention()
		{
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_attentionUser", DbType="VarChar(50)")]
		public string attentionUser
		{
			get
			{
				return this._attentionUser;
			}
			set
			{
				if ((this._attentionUser != value))
				{
					this._attentionUser = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Config")]
	public partial class Config
	{
		
		private string _name;
		
		private string _memo;
		
		private System.Nullable<bool> _turnOn;
		
		public Config()
		{
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_memo", DbType="VarChar(500)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this._memo = value;
				}
			}
		}
		
		[Column(Storage="_turnOn", DbType="Bit")]
		public System.Nullable<bool> turnOn
		{
			get
			{
				return this._turnOn;
			}
			set
			{
				if ((this._turnOn != value))
				{
					this._turnOn = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.House")]
	public partial class House
	{
		
		private string _userName;
		
		private System.Nullable<System.Guid> _pianoID;
		
		private System.Nullable<System.Guid> _sofaID;
		
		private System.Nullable<System.Guid> _frescoID;
		
		private System.Nullable<System.Guid> _floorID;
		
		private System.Nullable<System.Guid> _pendantLampID;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public House()
		{
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_pianoID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pianoID
		{
			get
			{
				return this._pianoID;
			}
			set
			{
				if ((this._pianoID != value))
				{
					this._pianoID = value;
				}
			}
		}
		
		[Column(Storage="_sofaID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> sofaID
		{
			get
			{
				return this._sofaID;
			}
			set
			{
				if ((this._sofaID != value))
				{
					this._sofaID = value;
				}
			}
		}
		
		[Column(Storage="_frescoID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> frescoID
		{
			get
			{
				return this._frescoID;
			}
			set
			{
				if ((this._frescoID != value))
				{
					this._frescoID = value;
				}
			}
		}
		
		[Column(Storage="_floorID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> floorID
		{
			get
			{
				return this._floorID;
			}
			set
			{
				if ((this._floorID != value))
				{
					this._floorID = value;
				}
			}
		}
		
		[Column(Storage="_pendantLampID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> pendantLampID
		{
			get
			{
				return this._pendantLampID;
			}
			set
			{
				if ((this._pendantLampID != value))
				{
					this._pendantLampID = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Opus")]
	public partial class Opus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _name;
		
		private string _userName;
		
		private string _mp3Path;
		
		private System.Nullable<int> _clickCount;
		
		private System.Nullable<int> _likeCount;
		
		private System.Nullable<int> _score;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void Onmp3PathChanging(string value);
    partial void Onmp3PathChanged();
    partial void OnclickCountChanging(System.Nullable<int> value);
    partial void OnclickCountChanged();
    partial void OnlikeCountChanging(System.Nullable<int> value);
    partial void OnlikeCountChanged();
    partial void OnscoreChanging(System.Nullable<int> value);
    partial void OnscoreChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Opus()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[Column(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_mp3Path", DbType="VarChar(500)")]
		public string mp3Path
		{
			get
			{
				return this._mp3Path;
			}
			set
			{
				if ((this._mp3Path != value))
				{
					this.Onmp3PathChanging(value);
					this.SendPropertyChanging();
					this._mp3Path = value;
					this.SendPropertyChanged("mp3Path");
					this.Onmp3PathChanged();
				}
			}
		}
		
		[Column(Storage="_clickCount", DbType="Int")]
		public System.Nullable<int> clickCount
		{
			get
			{
				return this._clickCount;
			}
			set
			{
				if ((this._clickCount != value))
				{
					this.OnclickCountChanging(value);
					this.SendPropertyChanging();
					this._clickCount = value;
					this.SendPropertyChanged("clickCount");
					this.OnclickCountChanged();
				}
			}
		}
		
		[Column(Storage="_likeCount", DbType="Int")]
		public System.Nullable<int> likeCount
		{
			get
			{
				return this._likeCount;
			}
			set
			{
				if ((this._likeCount != value))
				{
					this.OnlikeCountChanging(value);
					this.SendPropertyChanging();
					this._likeCount = value;
					this.SendPropertyChanged("likeCount");
					this.OnlikeCountChanged();
				}
			}
		}
		
		[Column(Storage="_score", DbType="Int")]
		public System.Nullable<int> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Users_Opus", Storage="_Users", ThisKey="userName", OtherKey="userName", IsForeignKey=true, DeleteRule="CASCADE")]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.Opus.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.Opus.Add(this);
						this._userName = value.userName;
					}
					else
					{
						this._userName = default(string);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.OpusComment")]
	public partial class OpusComment
	{
		
		private string _userName;
		
		private System.Nullable<System.Guid> _opusID;
		
		private string _comment;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		public OpusComment()
		{
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[Column(Storage="_opusID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> opusID
		{
			get
			{
				return this._opusID;
			}
			set
			{
				if ((this._opusID != value))
				{
					this._opusID = value;
				}
			}
		}
		
		[Column(Storage="_comment", DbType="VarChar(500)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this._dCreate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _password;
		
		private System.Nullable<byte> _gender;
		
		private string _email;
		
		private string _address;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _constellation;
		
		private System.Nullable<int> _scroe;
		
		private System.Nullable<short> _pianoLevel;
		
		private string _memo;
		
		private string _sinaWeiBo;
		
		private string _qq;
		
		private string _tencentWeiBo;
		
		private System.Nullable<System.DateTime> _dModified;
		
		private System.Nullable<System.DateTime> _dCreate;
		
		private EntitySet<Opus> _Opus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngenderChanging(System.Nullable<byte> value);
    partial void OngenderChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnconstellationChanging(string value);
    partial void OnconstellationChanged();
    partial void OnscroeChanging(System.Nullable<int> value);
    partial void OnscroeChanged();
    partial void OnpianoLevelChanging(System.Nullable<short> value);
    partial void OnpianoLevelChanged();
    partial void OnmemoChanging(string value);
    partial void OnmemoChanged();
    partial void OnsinaWeiBoChanging(string value);
    partial void OnsinaWeiBoChanged();
    partial void OnqqChanging(string value);
    partial void OnqqChanged();
    partial void OntencentWeiBoChanging(string value);
    partial void OntencentWeiBoChanged();
    partial void OndModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OndModifiedChanged();
    partial void OndCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndCreateChanged();
    #endregion
		
		public Users()
		{
			this._Opus = new EntitySet<Opus>(new Action<Opus>(this.attach_Opus), new Action<Opus>(this.detach_Opus));
			OnCreated();
		}
		
		[Column(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_gender", DbType="TinyInt")]
		public System.Nullable<byte> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="VarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[Column(Storage="_constellation", DbType="Char(10)")]
		public string constellation
		{
			get
			{
				return this._constellation;
			}
			set
			{
				if ((this._constellation != value))
				{
					this.OnconstellationChanging(value);
					this.SendPropertyChanging();
					this._constellation = value;
					this.SendPropertyChanged("constellation");
					this.OnconstellationChanged();
				}
			}
		}
		
		[Column(Storage="_scroe", DbType="Int")]
		public System.Nullable<int> scroe
		{
			get
			{
				return this._scroe;
			}
			set
			{
				if ((this._scroe != value))
				{
					this.OnscroeChanging(value);
					this.SendPropertyChanging();
					this._scroe = value;
					this.SendPropertyChanged("scroe");
					this.OnscroeChanged();
				}
			}
		}
		
		[Column(Storage="_pianoLevel", DbType="SmallInt")]
		public System.Nullable<short> pianoLevel
		{
			get
			{
				return this._pianoLevel;
			}
			set
			{
				if ((this._pianoLevel != value))
				{
					this.OnpianoLevelChanging(value);
					this.SendPropertyChanging();
					this._pianoLevel = value;
					this.SendPropertyChanged("pianoLevel");
					this.OnpianoLevelChanged();
				}
			}
		}
		
		[Column(Storage="_memo", DbType="VarChar(500)")]
		public string memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				if ((this._memo != value))
				{
					this.OnmemoChanging(value);
					this.SendPropertyChanging();
					this._memo = value;
					this.SendPropertyChanged("memo");
					this.OnmemoChanged();
				}
			}
		}
		
		[Column(Storage="_sinaWeiBo", DbType="VarChar(100)")]
		public string sinaWeiBo
		{
			get
			{
				return this._sinaWeiBo;
			}
			set
			{
				if ((this._sinaWeiBo != value))
				{
					this.OnsinaWeiBoChanging(value);
					this.SendPropertyChanging();
					this._sinaWeiBo = value;
					this.SendPropertyChanged("sinaWeiBo");
					this.OnsinaWeiBoChanged();
				}
			}
		}
		
		[Column(Storage="_qq", DbType="Char(20)")]
		public string qq
		{
			get
			{
				return this._qq;
			}
			set
			{
				if ((this._qq != value))
				{
					this.OnqqChanging(value);
					this.SendPropertyChanging();
					this._qq = value;
					this.SendPropertyChanged("qq");
					this.OnqqChanged();
				}
			}
		}
		
		[Column(Storage="_tencentWeiBo", DbType="VarChar(100)")]
		public string tencentWeiBo
		{
			get
			{
				return this._tencentWeiBo;
			}
			set
			{
				if ((this._tencentWeiBo != value))
				{
					this.OntencentWeiBoChanging(value);
					this.SendPropertyChanging();
					this._tencentWeiBo = value;
					this.SendPropertyChanged("tencentWeiBo");
					this.OntencentWeiBoChanged();
				}
			}
		}
		
		[Column(Storage="_dModified", DbType="Date")]
		public System.Nullable<System.DateTime> dModified
		{
			get
			{
				return this._dModified;
			}
			set
			{
				if ((this._dModified != value))
				{
					this.OndModifiedChanging(value);
					this.SendPropertyChanging();
					this._dModified = value;
					this.SendPropertyChanged("dModified");
					this.OndModifiedChanged();
				}
			}
		}
		
		[Column(Storage="_dCreate", DbType="Date", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> dCreate
		{
			get
			{
				return this._dCreate;
			}
			set
			{
				if ((this._dCreate != value))
				{
					this.OndCreateChanging(value);
					this.SendPropertyChanging();
					this._dCreate = value;
					this.SendPropertyChanged("dCreate");
					this.OndCreateChanged();
				}
			}
		}
		
		[Association(Name="Users_Opus", Storage="_Opus", ThisKey="userName", OtherKey="userName")]
		public EntitySet<Opus> Opus
		{
			get
			{
				return this._Opus;
			}
			set
			{
				this._Opus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opus(Opus entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_Opus(Opus entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
	}
}
#pragma warning restore 1591
